version: '3.8'

services:
  app:
    build: .
    container_name: app_movies
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: database_movies
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_PORT: 5432
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1-alpine3.18
    restart: always
    container_name: database_movies
    ports:
      - "5432:5432"
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    volumes:
      - ./db:/var/lib/postgresql/data
